name: Makefile CI

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: define versions
      run: |
        echo "PHP_VERSION=8.1" >> $GITHUB_ENV
        echo "MAXMINDDB_VERSION=1.6.0" >> $GITHUB_ENV
    
    - name: install php dev
      run: sudo apt upgrade && sudo apt install -y php${PHP_VERSION}-dev tree
    
    - name: get libmaxminddb
      run: wget https://github.com/maxmind/libmaxminddb/releases/download/${MAXMINDDB_VERSION}/libmaxminddb-${MAXMINDDB_VERSION}.tar.gz && tar xzf libmaxminddb-${MAXMINDDB_VERSION}.tar.gz
      
    - name: Compile and install
      run: cd libmaxminddb-${MAXMINDDB_VERSION} && ./configure && make && sudo make install
      
    - name: Get PHP ext
      run: git clone https://github.com/maxmind/MaxMind-DB-Reader-php.git
      
    - name: Compile
      run: cd MaxMind-DB-Reader-php/ext && phpize && ./configure && make && tree && sudo make install
      
    - name: Create archive
      run: cd MaxMind-DB-Reader-php/ext/modules && tar -czf maxminddb-${PHP_VERSION}-${MAXMINDDB_VERSION}-${GITHUB_REF_NAME}.tar.gz maxminddb.so

    - name: Create checksum
      run: cd MaxMind-DB-Reader-php/ext/modules && sha256sum maxminddb-${PHP_VERSION}-${MAXMINDDB_VERSION}-${GITHUB_REF_NAME}.tar.gz > sha256sums
      
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: |
          MaxMind-DB-Reader-php/ext/modules/maxminddb-*-${{ github.ref_name }}.tar.gz
          MaxMind-DB-Reader-php/ext/modules/sha256sums
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
